apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wikijs
type: Opaque
data:
  ROOT: cm9vdA==
  ROOT_PASSWORD: VGhpbmszMjEyISE1Nw==
  DATABASE: d2lraWpz
  USER: d2lraWpz
  PASSWORD: VGhpbmszMjEyISE1Nw==
